# Generated by Django 3.1.4 on 2021-01-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='employee',
            new_name='user',
        ),
    ]
